<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Seed the application's products.
     */
    public function run(): void
    {
        $products = [
            [
                'id' => 'oversized-logo-hoodie-abc12',
                'sku' => 'HOOD001',
                'name' => 'Oversized Logo Hoodie',
                'description' => 'Heavyweight 400gsm cotton hoodie with embroidered chest logo and kangaroo pocket. Relaxed oversized fit.',
                'price' => 129.00,
                'compare_at_price' => 159.00,
                'category' => 'Hoodies',
                'category_id' => 1,
                'image_url' => 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&q=80',
                'featured' => true,
                'status' => 'active',
                'stock_quantity' => 45,
                'tags' => 'oversized,logo,heavyweight,winter',
            ],
            [
                'id' => 'washed-black-hoodie-def34',
                'sku' => 'HOOD002',
                'name' => 'Washed Black Hoodie',
                'description' => 'Vintage washed black hoodie with distressed details. Pre-shrunk cotton blend.',
                'price' => 119.00,
                'compare_at_price' => null,
                'category' => 'Hoodies',
                'category_id' => 1,
                'image_url' => 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800&q=80',
                'featured' => false,
                'status' => 'active',
                'stock_quantity' => 32,
                'tags' => 'vintage,washed,black',
            ],
            [
                'id' => 'zip-up-essential-hoodie-ghi56',
                'sku' => 'HOOD003',
                'name' => 'Zip-Up Essential Hoodie',
                'description' => 'Clean minimal zip-up hoodie with metal hardware. Perfect for layering.',
                'price' => 99.00,
                'compare_at_price' => null,
                'category' => 'Hoodies',
                'category_id' => 1,
                'image_url' => 'https://images.unsplash.com/photo-1578681994506-b8f463449011?w=800&q=80',
                'featured' => false,
                'status' => 'active',
                'stock_quantity' => 28,
                'tags' => 'zip-up,minimal,essential',
            ],
            [
                'id' => 'graphic-print-tee-jkl78',
                'sku' => 'TEE001',
                'name' => 'Graphic Print Tee',
                'description' => 'Oversized t-shirt with bold chest graphic. 100% combed cotton, custom fit.',
                'price' => 59.00,
                'compare_at_price' => null,
                'category' => 'T-Shirts',
                'category_id' => 2,
                'image_url' => 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&q=80',
                'featured' => true,
                'status' => 'active',
                'stock_quantity' => 75,
                'tags' => 'graphic,oversized,print',
            ],
            [
                'id' => 'essential-box-logo-tee-mno90',
                'sku' => 'TEE002',
                'name' => 'Essential Box Logo Tee',
                'description' => 'Classic box logo t-shirt. Premium heavyweight cotton.',
                'price' => 49.00,
                'compare_at_price' => null,
                'category' => 'T-Shirts',
                'category_id' => 2,
                'image_url' => 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80',
                'featured' => false,
                'status' => 'active',
                'stock_quantity' => 120,
                'tags' => 'essential,box logo,classic',
            ],
            [
                'id' => 'vintage-racing-tee-pqr12',
                'sku' => 'TEE003',
                'name' => 'Vintage Racing Tee',
                'description' => 'Retro racing-inspired graphic tee with distressed print.',
                'price' => 55.00,
                'compare_at_price' => 69.00,
                'category' => 'T-Shirts',
                'category_id' => 2,
                'image_url' => 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&q=80',
                'featured' => false,
                'status' => 'active',
                'stock_quantity' => 42,
                'tags' => 'vintage,racing,retro',
            ],
            [
                'id' => 'cargo-joggers-stu34',
                'sku' => 'BOT001',
                'name' => 'Cargo Joggers',
                'description' => 'Utility cargo joggers with multiple pockets. Tapered fit with elastic cuffs.',
                'price' => 89.00,
                'compare_at_price' => null,
                'category' => 'Bottoms',
                'category_id' => 3,
                'image_url' => 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&q=80',
                'featured' => true,
                'status' => 'active',
                'stock_quantity' => 38,
                'tags' => 'cargo,joggers,utility',
            ],
            [
                'id' => 'wide-leg-pants-vwx56',
                'sku' => 'BOT002',
                'name' => 'Wide Leg Pants',
                'description' => 'Relaxed wide leg pants with adjustable waist. Japanese cotton twill.',
                'price' => 109.00,
                'compare_at_price' => null,
                'category' => 'Bottoms',
                'category_id' => 3,
                'image_url' => 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&q=80',
                'featured' => false,
                'status' => 'active',
                'stock_quantity' => 22,
                'tags' => 'wide leg,japanese,relaxed',
            ],
            [
                'id' => 'bomber-jacket-yza78',
                'sku' => 'OUT001',
                'name' => 'Bomber Jacket',
                'description' => 'Classic bomber jacket with satin finish. Ribbed collar and cuffs.',
                'price' => 179.00,
                'compare_at_price' => 219.00,
                'category' => 'Outerwear',
                'category_id' => 4,
                'image_url' => 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&q=80',
                'featured' => true,
                'status' => 'active',
                'stock_quantity' => 15,
                'tags' => 'bomber,satin,classic',
            ],
            [
                'id' => 'puffer-vest-bcd90',
                'sku' => 'OUT002',
                'name' => 'Puffer Vest',
                'description' => 'Quilted puffer vest with stand collar. Lightweight warmth.',
                'price' => 139.00,
                'compare_at_price' => null,
                'category' => 'Outerwear',
                'category_id' => 4,
                'image_url' => 'https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=800&q=80',
                'featured' => false,
                'status' => 'active',
                'stock_quantity' => 18,
                'tags' => 'puffer,vest,lightweight',
            ],
            [
                'id' => 'five-panel-cap-efg12',
                'sku' => 'ACC001',
                'name' => 'Five Panel Cap',
                'description' => 'Embroidered five panel cap with adjustable strap.',
                'price' => 45.00,
                'compare_at_price' => null,
                'category' => 'Accessories',
                'category_id' => 5,
                'image_url' => 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800&q=80',
                'featured' => false,
                'status' => 'active',
                'stock_quantity' => 85,
                'tags' => 'cap,embroidered,adjustable',
            ],
            [
                'id' => 'crossbody-bag-hij34',
                'sku' => 'ACC002',
                'name' => 'Crossbody Bag',
                'description' => 'Compact crossbody bag with multiple compartments.',
                'price' => 65.00,
                'compare_at_price' => null,
                'category' => 'Accessories',
                'category_id' => 5,
                'image_url' => 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80',
                'featured' => false,
                'status' => 'active',
                'stock_quantity' => 55,
                'tags' => 'bag,crossbody,compact',
            ],
        ];

        foreach ($products as $product) {
            DB::table('products')->insert([
                'id' => $product['id'],
                'sku' => $product['sku'],
                'name' => $product['name'],
                'description' => $product['description'],
                'price' => $product['price'],
                'compare_at_price' => $product['compare_at_price'],
                'category' => $product['category'],
                'category_id' => $product['category_id'],
                'image_url' => $product['image_url'],
                'featured' => $product['featured'],
                'status' => $product['status'],
                'stock_quantity' => $product['stock_quantity'],
                'tags' => $product['tags'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
